spring.application.name=SpringAiDemo
spring.ai.openai.api-key=${MY_APP_KEY}

# HTTP Client Configuration
spring.http.client.connect-timeout=30000
server.servlet.encoding.enabled=true
server.servlet.encoding.charset=UTF-8

# OpenAI Configuration
spring.ai.openai.base-url=https://api.openai.com/v1
